package com.example.cloudrive.ui.theme

import androidx.compose.ui.graphics.Color

// Brass (#E9B44C) accent on near-black surfaces — Music design system seed.
// Do not use these hex values as one-off colors in screens; always read via MaterialTheme.colorScheme.

val Brass = Color(0xFFE9B44C)
val BrassDark = Color(0xFFB98A2E)

val md_theme_light_primary = Color(0xFFB98A2E)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFFFDDA3)
val md_theme_light_onPrimaryContainer = Color(0xFF2A1800)
val md_theme_light_secondary = Color(0xFF6F5B3E)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFFADEB4)
val md_theme_light_onSecondaryContainer = Color(0xFF261904)
val md_theme_light_tertiary = Color(0xFF4C6247)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFCEE8C3)
val md_theme_light_onTertiaryContainer = Color(0xFF0B1F09)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onErrorContainer = Color(0xFF93000A)
val md_theme_light_background = Color(0xFFFFFBFF)
val md_theme_light_onBackground = Color(0xFF1E1B16)
val md_theme_light_surface = Color(0xFFFFFBFF)
val md_theme_light_onSurface = Color(0xFF1E1B16)
val md_theme_light_surfaceVariant = Color(0xFFEFE0CF)
val md_theme_light_onSurfaceVariant = Color(0xFF4F4539)
val md_theme_light_outline = Color(0xFF817567)
val md_theme_light_outlineVariant = Color(0xFFD3C4B4)
val md_theme_light_scrim = Color(0xFF000000)
val md_theme_light_inverseSurface = Color(0xFF34302A)
val md_theme_light_inverseOnSurface = Color(0xFFF8EFE7)
val md_theme_light_inversePrimary = Color(0xFFE9B44C)
val md_theme_light_surfaceDim = Color(0xFFE0D8CE)
val md_theme_light_surfaceBright = Color(0xFFFFFBFF)
val md_theme_light_surfaceContainerLowest = Color(0xFFFFFFFF)
val md_theme_light_surfaceContainerLow = Color(0xFFFAF1E7)
val md_theme_light_surfaceContainer = Color(0xFFF4EBE1)
val md_theme_light_surfaceContainerHigh = Color(0xFFEEE5DB)
val md_theme_light_surfaceContainerHighest = Color(0xFFE8E0D6)

// Dark surfaces per Music design spec: base #0C0D11, elevated #14161C, highest #1C1F27.
val md_theme_dark_primary = Color(0xFFE9B44C)
val md_theme_dark_onPrimary = Color(0xFF3E2E00)
val md_theme_dark_primaryContainer = Color(0xFF5A4400)
val md_theme_dark_onPrimaryContainer = Color(0xFFFFDDA3)
val md_theme_dark_secondary = Color(0xFFDDC2A1)
val md_theme_dark_onSecondary = Color(0xFF3D2E15)
val md_theme_dark_secondaryContainer = Color(0xFF56442A)
val md_theme_dark_onSecondaryContainer = Color(0xFFFADEB4)
val md_theme_dark_tertiary = Color(0xFFB2CCA7)
val md_theme_dark_onTertiary = Color(0xFF1F351B)
val md_theme_dark_tertiaryContainer = Color(0xFF354B30)
val md_theme_dark_onTertiaryContainer = Color(0xFFCEE8C3)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF0C0D11)
val md_theme_dark_onBackground = Color(0xFFE9E1D8)
val md_theme_dark_surface = Color(0xFF0C0D11)
val md_theme_dark_onSurface = Color(0xFFE9E1D8)
val md_theme_dark_surfaceVariant = Color(0xFF4F4539)
val md_theme_dark_onSurfaceVariant = Color(0xFFD3C4B4)
val md_theme_dark_outline = Color(0xFF9C8F80)
val md_theme_dark_outlineVariant = Color(0xFF4F4539)
val md_theme_dark_scrim = Color(0xFF000000)
val md_theme_dark_inverseSurface = Color(0xFFE9E1D8)
val md_theme_dark_inverseOnSurface = Color(0xFF34302A)
val md_theme_dark_inversePrimary = Color(0xFFB98A2E)
val md_theme_dark_surfaceDim = Color(0xFF0C0D11)
val md_theme_dark_surfaceBright = Color(0xFF34363E)
val md_theme_dark_surfaceContainerLowest = Color(0xFF07080B)
val md_theme_dark_surfaceContainerLow = Color(0xFF14161C)
val md_theme_dark_surfaceContainer = Color(0xFF181A21)
val md_theme_dark_surfaceContainerHigh = Color(0xFF1C1F27)
val md_theme_dark_surfaceContainerHighest = Color(0xFF272A33)
